### ISSUE TITLE
HTTPSConnection error upon install

### ISSUE THREAD

**Issue by darkvertex** [rozboris/Sublime-Tweet#10]
Right after install via PackageControl, I got this in my console:

Traceback (most recent call last):
  File "./sublime_plugin.py", line 62, in reload_plugin
  File "./SublimeTweet.py", line 6, in <module>
    import libs.twitter
  File "./libs/twitter.py", line 66, in <module>
    import oauth2 as oauth
  File "./libs/oauth2.py", line 31, in <module>
    import httplib2
  File "./libs/httplib2.py", line 795, in <module>
    class HTTPSConnectionWithTimeout(httplib.HTTPSConnection):
AttributeError: 'module' object has no attribute 'HTTPSConnection'

After some googling, it seems HTTPSConnection is only available in Python 2.7. My Sublime is running 2.6.

**Comment by rozboris** [comment]
Will be fixed while porting to ST3 (#13)
