### ISSUE TITLE
I get this error after installing (st2/win7)

### ISSUE THREAD

**Issue by karacas** [rozboris/Sublime-Tweet#9]
No internet connection, sorry!
Unhandled exception in thread started by <function checkInternetConnection at 0x00000000087AE128>
Traceback (most recent call last):
  File ".\SublimeTweet.py", line 303, in checkInternetConnection
  File ".\SublimeTweet.py", line 29, in setInternetStatus
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)

**Comment by rozboris** [comment]
Fixed in v.1.0.0. Please update from Package Control!
